"use client";

import React, { useState } from "react";
import { Button } from "@/components/ui/Button";

const mockMatches = [
  {
    id: "M-4890",
    source: { name: "Plot 88-A, Phase II", id: "P-4482", dataset: "Cadastral Baseline" },
    candidate: { name: "Property 88A", id: "MCD-781", dataset: "Municipal GIS" },
    type: "Geometry + Attribute",
    confidence: 82.4,
    evidence: { iou: "88.1%", distance: "1.2m", attributes: "Address match" },
    status: "review",
    conflict: "Area variance of +14.2 m² in candidate."
  },
  {
    id: "M-4891",
    source: { name: "Sector 7, Block B", id: "P-4483", dataset: "Cadastral Baseline" },
    candidate: { name: "Sect-7/B", id: "MCD-782", dataset: "Municipal GIS" },
    type: "Topology Exact",
    confidence: 99.2,
    evidence: { iou: "99.8%", distance: "0.1m", attributes: "Exact match" },
    status: "matched",
    conflict: null
  },
  {
    id: "M-4892",
    source: { name: "Park Reserve 2", id: "P-4484", dataset: "Cadastral Baseline" },
    candidate: { name: "Unassigned Zone", id: "MCD-912", dataset: "Municipal GIS" },
    type: "Partial Overlap",
    confidence: 45.0,
    evidence: { iou: "42.5%", distance: "8.5m", attributes: "Mismatch" },
    status: "unresolved",
    conflict: "Candidate spans multiple cadastral parcels."
  },
  {
    id: "M-4893",
    source: { name: "Commercial Hub C", id: "P-4485", dataset: "Cadastral Baseline" },
    candidate: { name: "Comm-C", id: "MCD-804", dataset: "Municipal GIS" },
    type: "Attribute Only",
    confidence: 12.5,
    evidence: { iou: "0.0%", distance: "450m", attributes: "Name match" },
    status: "rejected",
    conflict: "Geometries are entirely disjointed."
  }
];

export default function MatchesPage() {
  const [expandedId, setExpandedId] = useState<string | null>(null);

  const toggleExpand = (id: string) => {
    setExpandedId(expandedId === id ? null : id);
  };

  return (
    <div className="max-w-7xl mx-auto flex flex-col gap-8">
      {/* Header Section */}
      <div className="flex flex-col md:flex-row md:items-start justify-between gap-4">
        <div>
          <h1 className="text-headline-lg font-bold text-primary tracking-tight">Match Review</h1>
          <p className="text-body-md text-neutral mt-2 max-w-2xl">
            Review candidate spatial entity matches generated by the harmonization engine and resolve boundary conflicts.
          </p>
        </div>
        <div className="shrink-0 flex items-center gap-3">
          <Button variant="secondary" className="flex items-center gap-2 shadow-sm">
            <span className="material-symbols-outlined text-[18px]">rule</span>
            Update Ruleset
          </Button>
          <Button variant="primary" className="flex items-center gap-2 shadow-sm">
            <span className="material-symbols-outlined text-[18px]">done_all</span>
            Auto-Resolve Safe Matches
          </Button>
        </div>
      </div>

      {/* Summary Cards */}
      <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
        <div className="bg-surface border border-border p-4 rounded-lg shadow-sm flex flex-col">
          <span className="text-label-spatial-header text-neutral uppercase font-bold tracking-wider mb-1">Total Matches</span>
          <span className="text-headline-md font-bold text-primary mt-1">1,248</span>
        </div>
        <div className="bg-surface border border-border p-4 rounded-lg shadow-sm flex flex-col">
          <span className="text-label-spatial-header text-neutral uppercase font-bold tracking-wider mb-1">Auto-Matched</span>
          <span className="text-headline-md font-bold text-cadastral-emerald mt-1">1,192</span>
        </div>
        <div className="bg-variance-amber-subtle border border-variance-amber-border p-4 rounded-lg shadow-sm flex flex-col">
          <span className="text-label-spatial-header text-variance-amber uppercase font-bold tracking-wider mb-1">Needs Review</span>
          <span className="text-headline-md font-bold text-variance-amber mt-1">45</span>
        </div>
        <div className="bg-blueprint-blue border border-blueprint-border p-4 rounded-lg shadow-sm flex flex-col">
          <span className="text-label-spatial-header text-secondary uppercase font-bold tracking-wider mb-1">Unmatched</span>
          <span className="text-headline-md font-bold text-secondary mt-1">11</span>
        </div>
      </div>

      {/* Toolbar (Search & Filter) */}
      <div className="bg-surface border border-border p-3 rounded-lg shadow-sm flex flex-col md:flex-row items-center gap-4 justify-between">
        <div className="relative w-full md:w-80">
          <span className="material-symbols-outlined absolute left-3 top-1/2 -translate-y-1/2 text-[18px] text-neutral">search</span>
          <input 
            type="text" 
            placeholder="Search match ID or parcel ID..." 
            className="w-full bg-background border border-border rounded-md pl-9 pr-3 py-1.5 text-body-sm font-medium text-primary focus:outline-none focus:border-secondary focus:ring-1 focus:ring-secondary transition-all"
          />
        </div>
        <div className="flex items-center gap-3 w-full md:w-auto overflow-x-auto">
          <button className="flex items-center gap-1.5 text-body-sm font-medium text-neutral hover:text-primary transition-colors bg-background border border-border px-3 py-1.5 rounded-md whitespace-nowrap">
            Status: Needs Review
            <span className="material-symbols-outlined text-[16px]">arrow_drop_down</span>
          </button>
          <button className="flex items-center gap-1.5 text-body-sm font-medium text-neutral hover:text-primary transition-colors bg-background border border-border px-3 py-1.5 rounded-md whitespace-nowrap">
            Confidence: Any
            <span className="material-symbols-outlined text-[16px]">arrow_drop_down</span>
          </button>
          <button className="flex items-center gap-1.5 text-body-sm font-medium text-neutral hover:text-primary transition-colors bg-background border border-border px-3 py-1.5 rounded-md whitespace-nowrap">
            Type: Geometry
            <span className="material-symbols-outlined text-[16px]">arrow_drop_down</span>
          </button>
        </div>
      </div>

      {/* Matches List */}
      <div className="flex flex-col gap-3 pb-8">
        {mockMatches.map((match) => {
          const isExpanded = expandedId === match.id;
          
          let statusStyles = "";
          let statusIcon = "";
          let statusText = "";

          switch (match.status) {
            case "matched":
              statusStyles = "bg-cadastral-emerald-subtle text-cadastral-emerald border-cadastral-emerald-border";
              statusIcon = "verified";
              statusText = "Matched";
              break;
            case "review":
              statusStyles = "bg-variance-amber-subtle text-variance-amber border-variance-amber-border";
              statusIcon = "warning";
              statusText = "Review";
              break;
            case "unresolved":
              statusStyles = "bg-blueprint-blue text-secondary border-blueprint-border";
              statusIcon = "help";
              statusText = "Unresolved";
              break;
            case "rejected":
              statusStyles = "bg-conflict-rose-subtle text-conflict-rose border-conflict-rose-border";
              statusIcon = "cancel";
              statusText = "Rejected";
              break;
          }

          return (
            <div key={match.id} className="bg-surface border border-border rounded-xl shadow-tier-1 hover:shadow-tier-2 transition-shadow overflow-hidden flex flex-col">
              {/* Row Header / Summary */}
              <div 
                className="p-4 flex flex-col xl:flex-row xl:items-center justify-between gap-4 cursor-pointer"
                onClick={() => toggleExpand(match.id)}
              >
                
                {/* Identifier & Match Info */}
                <div className="flex items-center gap-6 xl:w-2/5">
                  <div className="flex flex-col gap-1 w-20 shrink-0">
                    <span className="font-mono text-label-data-mono text-neutral">ID</span>
                    <span className="font-mono font-bold text-body-sm text-primary">{match.id}</span>
                  </div>
                  
                  <div className="flex flex-col gap-1">
                    <span className="text-[10px] uppercase font-bold text-cadastral-emerald">{match.source.dataset}</span>
                    <div className="flex items-center gap-2">
                      <span className="font-bold text-body-sm text-primary">{match.source.name}</span>
                      <span className="font-mono text-[10px] bg-background border border-border px-1.5 py-0.5 rounded text-neutral">{match.source.id}</span>
                    </div>
                  </div>
                  
                  <span className="material-symbols-outlined text-neutral opacity-50 shrink-0 hidden md:block">swap_horiz</span>
                  
                  <div className="flex flex-col gap-1">
                    <span className="text-[10px] uppercase font-bold text-secondary">{match.candidate.dataset}</span>
                    <div className="flex items-center gap-2">
                      <span className="font-bold text-body-sm text-primary">{match.candidate.name}</span>
                      <span className="font-mono text-[10px] bg-background border border-border px-1.5 py-0.5 rounded text-neutral">{match.candidate.id}</span>
                    </div>
                  </div>
                </div>

                {/* Metrics & Evidence */}
                <div className="flex items-center gap-6 xl:w-2/5 justify-between xl:justify-start">
                  <div className="flex flex-col">
                    <span className="text-[10px] uppercase font-bold text-neutral">Type</span>
                    <span className="text-body-sm text-primary font-medium mt-1">{match.type}</span>
                  </div>
                  
                  <div className="flex flex-col items-center">
                    <span className="text-[10px] uppercase font-bold text-neutral">Confidence</span>
                    <span className={`text-body-md font-mono font-bold mt-0.5 ${match.confidence > 90 ? 'text-cadastral-emerald' : match.confidence > 50 ? 'text-variance-amber' : 'text-conflict-rose'}`}>
                      {match.confidence}%
                    </span>
                  </div>

                  <div className="hidden md:flex flex-col">
                    <span className="text-[10px] uppercase font-bold text-neutral">Evidence</span>
                    <div className="flex items-center gap-1.5 mt-1">
                      <span className="text-[10px] font-mono bg-background border border-border px-1.5 py-0.5 rounded text-neutral">IoU: {match.evidence.iou}</span>
                      <span className="text-[10px] font-mono bg-background border border-border px-1.5 py-0.5 rounded text-neutral">Dist: {match.evidence.distance}</span>
                    </div>
                  </div>
                </div>

                {/* Status & Actions */}
                <div className="flex items-center gap-4 xl:w-1/5 justify-end">
                  <div className={`px-2.5 py-1 rounded-md text-[10px] font-bold uppercase border flex items-center gap-1 ${statusStyles}`}>
                    <span className="material-symbols-outlined text-[14px]">{statusIcon}</span>
                    {statusText}
                  </div>
                  <button className="w-8 h-8 rounded flex items-center justify-center text-neutral hover:bg-surface-container-low transition-colors border border-border">
                    <span className="material-symbols-outlined text-[20px] transition-transform duration-200" style={{ transform: isExpanded ? 'rotate(180deg)' : 'rotate(0deg)' }}>
                      expand_more
                    </span>
                  </button>
                </div>
              </div>

              {/* Expanded Comparison Area */}
              {isExpanded && (
                <div className="border-t border-border bg-background p-4 flex flex-col lg:flex-row gap-6">
                  {/* Left: Interactive Map Viewer */}
                  <div className="flex-1 bg-surface border border-border rounded-lg relative overflow-hidden h-64 shadow-inner">
                    <svg className="absolute inset-0 w-full h-full text-border opacity-50" xmlns="http://www.w3.org/2000/svg">
                      <defs>
                        <pattern id="match-grid" width="20" height="20" patternUnits="userSpaceOnUse">
                          <path d="M 20 0 L 0 0 0 20" fill="none" stroke="currentColor" strokeWidth="0.5"></path>
                        </pattern>
                      </defs>
                      <rect width="100%" height="100%" fill="url(#match-grid)"></rect>
                    </svg>

                    <div className="absolute top-2 right-2 bg-surface/90 border border-border rounded p-1.5 flex flex-col gap-1 text-[10px] font-mono shadow-sm z-10">
                      <div className="flex items-center gap-1.5">
                        <span className="w-2 h-2 rounded bg-cadastral-emerald"></span>
                        <span className="text-neutral">Baseline</span>
                      </div>
                      <div className="flex items-center gap-1.5">
                        <span className="w-2 h-2 rounded bg-secondary border border-secondary border-dashed"></span>
                        <span className="text-neutral">Candidate</span>
                      </div>
                    </div>

                    <svg className="absolute inset-0 w-full h-full" viewBox="0 0 400 250" fill="none" xmlns="http://www.w3.org/2000/svg">
                      {match.confidence > 50 ? (
                        <>
                          {/* Simulated overlapping geometry */}
                          <polygon points="120,60 280,45 300,190 140,210" fill="#059669" fillOpacity="0.1" stroke="#059669" strokeWidth="2"></polygon>
                          <polygon points="110,65 270,55 310,180 130,200" fill="#2563EB" fillOpacity="0.1" stroke="#2563EB" strokeWidth="1.5" strokeDasharray="4 4"></polygon>
                          {match.status === "review" && (
                            <circle cx="290" cy="185" r="15" fill="#D97706" fillOpacity="0.2" stroke="#D97706" strokeWidth="1"></circle>
                          )}
                        </>
                      ) : (
                        <>
                          {/* Disjointed geometry */}
                          <polygon points="80,80 150,70 160,140 90,150" fill="#059669" fillOpacity="0.1" stroke="#059669" strokeWidth="2"></polygon>
                          <polygon points="260,110 330,100 340,170 270,180" fill="#2563EB" fillOpacity="0.1" stroke="#2563EB" strokeWidth="1.5" strokeDasharray="4 4"></polygon>
                          <line x1="160" y1="140" x2="260" y2="110" stroke="#E11D48" strokeWidth="1.5" strokeDasharray="4 4"></line>
                          <foreignObject x="180" y="95" width="60" height="20">
                            <div className="text-[9px] font-mono text-conflict-rose bg-surface/80 rounded px-1">450m Δ</div>
                          </foreignObject>
                        </>
                      )}
                    </svg>
                  </div>

                  {/* Right: Details & Actions */}
                  <div className="w-full lg:w-80 flex flex-col gap-4">
                    <div className="bg-surface border border-border rounded-lg p-3 shadow-sm text-body-sm flex flex-col gap-2">
                      <div className="flex justify-between border-b border-border pb-1.5">
                        <span className="text-neutral font-medium">Attribute Match</span>
                        <span className="font-mono text-primary font-bold">{match.evidence.attributes}</span>
                      </div>
                      <div className="flex justify-between border-b border-border pb-1.5">
                        <span className="text-neutral font-medium">Centroid Distance</span>
                        <span className="font-mono text-primary font-bold">{match.evidence.distance}</span>
                      </div>
                      <div className="flex justify-between">
                        <span className="text-neutral font-medium">Area Overlap (IoU)</span>
                        <span className="font-mono text-primary font-bold">{match.evidence.iou}</span>
                      </div>
                    </div>

                    {match.conflict && (
                      <div className="bg-variance-amber-subtle border border-variance-amber-border rounded-lg p-3 text-[11px] text-variance-amber font-mono flex items-start gap-1.5 shadow-sm">
                        <span className="material-symbols-outlined text-[14px]">warning</span>
                        {match.conflict}
                      </div>
                    )}

                    <div className="flex flex-col gap-2 mt-auto">
                      {match.status === 'review' || match.status === 'unresolved' ? (
                        <>
                          <button className="w-full bg-cadastral-emerald hover:bg-[#047857] text-surface font-semibold text-body-sm py-2 rounded-md transition-colors shadow-sm flex items-center justify-center gap-1.5">
                            <span className="material-symbols-outlined text-[16px]">check</span>
                            Accept Match
                          </button>
                          <div className="grid grid-cols-2 gap-2">
                            <button className="bg-surface border border-border hover:bg-surface-container-low text-primary font-semibold text-body-sm py-2 rounded-md transition-colors shadow-sm">
                              Mark Distinct
                            </button>
                            <button className="bg-conflict-rose-subtle text-conflict-rose border border-conflict-rose-border hover:bg-[#FECDD3] font-semibold text-body-sm py-2 rounded-md transition-colors shadow-sm">
                              Reject
                            </button>
                          </div>
                        </>
                      ) : (
                        <button className="bg-surface border border-border hover:bg-surface-container-low text-primary font-semibold text-body-sm py-2 rounded-md transition-colors shadow-sm flex items-center justify-center gap-1.5">
                          <span className="material-symbols-outlined text-[16px]">undo</span>
                          Reopen Review
                        </button>
                      )}
                    </div>
                  </div>
                </div>
              )}
            </div>
          );
        })}
      </div>
    </div>
  );
}
